// Number of genuinely different source photos supplied for each project before
// the display gallery was expanded. This keeps real multi-angle projects ahead
// of single-photo projects while preserving the existing order within a tier.
export const caseSourceImageCount: Record<string, number> = {
  "carry-case-corporate-gift-series": 12,
  "custom-corporate-commemorative-coin-gift-box": 10,
  "bespoke-executive-corporate-gift-set": 10,
  "19-piece-outdoor-cooking-seasoning-organizer-set": 10,
  "full-executive-custom-gift-set-six-piece": 10,
  "rosewood-rotating-commemorative-coin-display-box": 10,
  "sage-green-corporate-gift-set": 10,
  "suede-texture-coffee-cup-gift-set": 10,
  "monochrome-executive-corporate-gift-set": 10,
  "multi-color-organizer-notebook-set": 5,
  "royal-blue-tech-business-set": 5,
  "woodgrain-five-piece-business-set": 5,
  "color-block-business-gift-set": 4,
  "global-creative-office-set": 4,
  "minimal-grey-pen-notebook-set": 4,
  "natural-wood-corporate-set": 4,
  "red-notebook-tumbler-series": 4,
  "tri-color-administrative-set": 4,
  "blue-logistics-service-set": 4,
  "bamboo-texture-executive-set": 3,
  "graphite-office-trio": 3,
  "minimal-notebook-tumbler-set": 3,
  "vivid-corporate-welcome-set": 3,
  "navy-travel-office-set": 3,
  "blue-black-minimal-office-set": 3,
  "black-notebook-tumbler-set": 3,
  "monochrome-business-essentials": 3,
  "event-photo-commemorative-set": 3,
  "red-executive-gift-series": 3,
  "two-tone-basic-office-set": 3,
  "portable-corporate-carry-set": 3,
  "passport-commemorative-travel-set": 3,
  "express-staff-office-kit": 3,
  "white-tech-accessory-set": 2,
  "orange-event-office-set": 2,
  "grey-gold-executive-gift-set": 2,
  "red-fragrance-corporate-set": 2,
  "sage-care-gift-set": 2,
  "emerald-administrative-set": 2,
  "black-five-piece-corporate-kit": 2,
  "charcoal-office-welcome-set": 2,
  "black-gold-leather-gift-set": 2,
  "forest-green-travel-set": 2,
};
